### ISSUE TITLE
csv parse error

### ISSUE THREAD

**Issue by ZwizuHoM** [ScottyThePilot/hoi4_province_editor#14]
trying to drag in any map folder from any mod or simply base game, gives me the following error
Error: csv parse error: too few or too many columns were found

i use VSC text editor

**Comment by ScottyThePilot** [comment]
Try the [latest release](https://github.com/ScottyThePilot/hoi4_province_editor/releases/latest). I believe I've fixed the bug, as the base game map and OWB's map are now both loading correctly for me.

**Comment by ZwizuHoM** [comment]
it has indeed worked! thank you very much
